pipeline {

    agent { label 'worker1' }

    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = credentials('AWS_DEFAULT_REGION')
        CLUSTER_NAME = credentials('CLUSTER_NAME')
        REGISTRY = credentials('REGISTRY')
        SERVICE_NAME = 'mifosapp-service'
        VERSION = sh (script: 'git rev-parse HEAD', returnStdout: true).trim().take(10)
        NAMESPACE = "${env.GIT_BRANCH == 'production' ? 'production' : 'staging' }"
        JAVA_HOME = '/opt/jdk-17'
    }


    stages{

        stage("build") {
            steps{
                script {
                    // Build the project using Gradle and skip tests
                    sh './gradlew clean bootJar'
                    echo 'Build with Gradle'
                }
            }   
        }

        stage("Image Build") {
            steps{
                script {
                    // Use Jib to build Docker image instead of docker.build
                    echo 'Building Docker image with Jib'
                    sh './gradlew :fineract-provider:jibDockerBuild -x test'
                    sh "docker tag ${REGISTRY}/${SERVICE_NAME}:${VERSION}"
                    //dockerImage = docker.build "${REGISTRY}/${SERVICE_NAME}:${VERSION}"
                }
            }   
        }
        stage("ECR") {
            steps{
                script {
                    sh "aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin ${REGISTRY}"
                }
            }   
        }

        stage("Pushing to AWS ECR") {
            steps{
                script {
                    // Push the image built with Jib to AWS ECR
                    echo 'Pushing Docker image to ECR'
                    sh "docker push ${REGISTRY}/${SERVICE_NAME}:${VERSION}"
                }
            }   
        }
	    
        stage('Deploy') {
            steps {
                script {
                    dir('devops') {
                        sh '''
                            chmod +x ./deploy.sh
                            ./deploy.sh
                            '''
                    }
                }
            }
        }

         stage('Cleanup') {
            steps {
                script {
                    // Cleanup Docker image after deployment to free up space
                    echo "Cleaning up Docker images..."

                    // Remove the Docker image from the Jenkins worker1
                    sh 'docker image prune -f'
                    sh "docker rmi ${REGISTRY}/${SERVICE_NAME}:${VERSION} || true"
                    
                    // Prune unused Docker objects containers and volumes
                    sh "docker system prune -f --volumes || true"
                }
            }
        }
        
    }
}